### ISSUE TITLE
Linking reinforcement algorithms to the repo

### ISSUE THREAD

**Issue by vanhecke1** [deepmind/ai-safety-gridworlds#11]
Hi,

In the research paper, you have said that you trained two deep RL algorithms in the environments. But, I had trouble incorporating these RL algorithms to the environments and I couldn't find the implementation in this repository. If it is possible, where I can find the implementations, or some pointers about how to implement RL algorithms in the enviroments?

Thanks a lot!

**Comment by miljanm** [comment]
Hi,

At the moment we don't have the agents we used on these environments in the public domain. However, there are a large number of open source implementations of the agents we studied.

As a good starting point I would recommend having a look at tabular Q-learning and SARSA as described in [Sutton & Barto](http://incompleteideas.net/book/bookdraft2017nov5.pdf). Various python implementations of these algorithms should be easy to find on Google. 

For more complex agents, such as DQN, a great starting point are OpenAI reference agent implementations which can be found [here](https://github.com/openai/gym/blob/master/docs/agents.md). Although please note that these are made with python3 in mind, so they might not work out of the box with our environments which are python2 (this will change soon though, as we will be releasing python3 support in the near future).

In either case, some slight modification will be necessary in order to make the agent-environment connection conform to our interface.

**Comment by jvmncs** [comment]
For others who stumble on this, I've provided links to some examples of how to interface with the safety gridworlds in #14.

**Comment by miljanm** [comment]
Thanks for this, it's a great starting reference!
