### ISSUE TITLE
Environment usage

### ISSUE THREAD

**Issue by hari-sikchi** [deepmind/ai-safety-gridworlds#14]
Is there a documentation on using the environment for use with custom RL agents?

**Comment by jvmncs** [comment]
If you're interested, I've written a [library](https://github.com/jvmancuso/safe-grid-agents) with collaborators that allows you to more easily implement custom RL agents in these gridworlds.  [This commit](https://github.com/jvmancuso/safe-grid-agents/tree/4736db3c29b2f881bb4b541f668f89a13be4b3e0/safe_grid_agents/common/agents) was the last one for that repo that used the pycolab-style API included here.  In particular, [this file](https://github.com/jvmancuso/safe-grid-agents/blob/4736db3c29b2f881bb4b541f668f89a13be4b3e0/safe_grid_agents/common/learn.py) demonstrates how to use the environment in common training loops (in this case, for use with PPO and DQN style training loops).

In our more recent version of that library, we ended up wrapping the gridworlds inside a Gym API so that we could eventually drop in existing agent code written for Gym.  You can find that [here](https://github.com/david-lindner/safe-grid-gym).

**Comment by hari-sikchi** [comment]
Thanks for the prompt reply. It's much better than how I was using this work previously.
```
environment_name = "side_effects_sokoban"
env = factory.get_environment_obj(environment_name)
actions = [Actions.LEFT,Actions.RIGHT,Actions.UP,Actions.DOWN]
env.reset()
for action in actions:
    timestep = env.step(action)
    print(action)
    print(timestep.reward)
    print(timestep.observation)
    episode_return += timestep.reward if timestep.reward else 0
```

**Comment by 2phx** [comment]
Just following up on same question, there are so many examples on gym environments but I didn't find any  example of agent applied to gridworlds. 
Gridworlds are more valuable to me, would be great if anyone could share any simple example of agent use on gridworlds.
